CREATE TABLE TARGET_PERSONALISATION (
    CUSTOMER_SYS_GEN_ID BIGINT NOT NULL,
    PERSONALISATION_TYPE VARCHAR(100) NOT NULL,
    PERSONALISATION_KEY VARCHAR(200) NOT NULL,
    PERSONALISATION_VALUE VARCHAR(4000),
    SOURCE_UPDATED_AT DATETIME(6),
    MIGRATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (CUSTOMER_SYS_GEN_ID, PERSONALISATION_TYPE, PERSONALISATION_KEY),
    KEY IDX_TARGET_CUSTOMER (CUSTOMER_SYS_GEN_ID)
);
