CREATE TABLE PERSONALISATION_MIGRATION_STAGE (
    STAGE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_SYS_GEN_ID BIGINT NOT NULL,
    PERSONALISATION_TYPE VARCHAR(100) NOT NULL,
    PERSONALISATION_KEY VARCHAR(200) NOT NULL,
    PERSONALISATION_VALUE VARCHAR(4000),
    SOURCE_CREATED_AT TIMESTAMP,
    SOURCE_UPDATED_AT TIMESTAMP,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    RUN_ID VARCHAR(150),
    CLAIMED_BY VARCHAR(150),
    CLAIMED_AT TIMESTAMP,
    LAST_HEARTBEAT_AT TIMESTAMP,
    RETRY_COUNT INTEGER NOT NULL DEFAULT 0,
    COMPLETED_AT TIMESTAMP,
    ERROR_CODE VARCHAR(100),
    ERROR_MESSAGE VARCHAR(2000),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (STAGE_ID)
);

CREATE INDEX IDX_PMS_PENDING
ON PERSONALISATION_MIGRATION_STAGE (STATUS, CUSTOMER_SYS_GEN_ID, STAGE_ID);

CREATE INDEX IDX_PMS_RUN
ON PERSONALISATION_MIGRATION_STAGE (RUN_ID, CLAIMED_BY, STATUS, CUSTOMER_SYS_GEN_ID);

CREATE INDEX IDX_PMS_STALE
ON PERSONALISATION_MIGRATION_STAGE (STATUS, LAST_HEARTBEAT_AT);

CREATE UNIQUE INDEX UK_PMS_BUSINESS_KEY
ON PERSONALISATION_MIGRATION_STAGE
(CUSTOMER_SYS_GEN_ID, PERSONALISATION_TYPE, PERSONALISATION_KEY);

CREATE INDEX IDX_PMS_RUN_ACTIVITY
ON PERSONALISATION_MIGRATION_STAGE (RUN_ID, UPDATED_AT, STATUS);

CREATE INDEX IDX_PMS_VERIFY_CUSTOMER
ON PERSONALISATION_MIGRATION_STAGE (CUSTOMER_SYS_GEN_ID, PERSONALISATION_TYPE, PERSONALISATION_KEY);
